spring:
  datasource:
    url: jdbc:h2:mem:testes
    username: test
    password: 123
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
